"""Run every task and write results/RESULTS.md plus figures.

    uv run python -m atler_ml.bench            # 40 users x 1 year
    uv run python -m atler_ml.bench --quick    # 8 users, for CI
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from . import anomaly, categorise, recurring, synth  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "results"


def _table(df: pd.DataFrame, pct: list[str]) -> str:
    df = df.copy()
    for c in pct:
        df[c] = (100 * df[c]).map(lambda v: f"{v:.1f}")
    return df.to_markdown(index=False)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()
    users = 8 if args.quick else 40
    out = OUT / "quick" if args.quick else OUT  # quick runs never overwrite the committed results
    out.mkdir(parents=True, exist_ok=True)
    t0 = time.time()

    df = synth.generate(users=users, seed=args.seed)
    print(f"{len(df)} transactions, {users} users, {df['sub_id'].nunique()} recurring series, "
          f"{int(df['anomaly'].sum())} anomalies")

    cat = categorise.score(categorise.run(df))
    print(cat.pivot(index="k", columns="method", values="accuracy").round(3))

    rec = recurring.run(df)
    rec_table = pd.DataFrame([{"method": m, **{k: v for k, v in rec[m].items()}} for m in ("atler", "gbm")])
    print(rec_table)

    an = anomaly.score(anomaly.run(df, rec["names"]))
    print(an)

    # figure: accuracy vs how many expenses you've filed
    fig, ax = plt.subplots(figsize=(7, 4.2))
    for m, g in cat.groupby("method", sort=False):
        ax.plot(g["k"], 100 * g["accuracy"], marker="o", label=m)
    ax.set_xscale("log")
    ax.set_xticks(categorise.KS, [str(k) for k in categorise.KS])
    ax.set_xlabel("expenses you've filed (k)")
    ax.set_ylabel("accuracy on the rest (%)")
    ax.set_title("Category suggestions: accuracy vs labels")
    ax.grid(alpha=0.3)
    ax.legend(frameon=False, fontsize=9)
    fig.tight_layout()
    fig.savefig(out / "categorise.png", dpi=150)

    acc = cat.pivot(index="k", columns="method", values="accuracy")[categorise.METHODS].reset_index()
    f1 = cat.pivot(index="k", columns="method", values="macro_f1")[categorise.METHODS].reset_index()
    report = f"""# Results

Generated by `python -m atler_ml.bench{' --quick' if args.quick else ''}` (seed {args.seed}) in {time.time() - t0:.0f} s.
Data: {len(df):,} synthetic transactions from {users} users over one year, {df['sub_id'].nunique()} recurring series,
{int(df['anomaly'].sum())} planted anomalies. ATLER methods are ATLER's own TypeScript, run through `bridge/atler.ts`.

## 1. Category suggestions

Accuracy (%) on every later expense after you've filed the first k yourself:

{_table(acc, categorise.METHODS)}

Macro-F1 (%), which weights rare categories the same as common ones:

{_table(f1, categorise.METHODS)}

![accuracy vs k](categorise.png)

## 2. Subscription finder

Over {rec['eligible']} real recurring series (3+ charges, or 2+ for yearly plans):

{_table(rec_table, ['precision', 'recall', 'f1', 'cycle_accuracy'])}

## 3. Unusual spending

{_table(an, ['precision', 'recall', 'f1', 'pr_auc'])}
"""
    (out / "RESULTS.md").write_text(report)
    print(f"wrote {out / 'RESULTS.md'} in {time.time() - t0:.0f} s")


if __name__ == "__main__":
    main()
